### ISSUE TITLE
JOSS Review: Documentation -- Example Usage

### ISSUE THREAD

**Issue by CFGrote** [jonathanHuwP/CrystalGrowthTracker#22]
- [x] Provide a documented example where cgt is applied to real or realistic simulated data. Ideally, this would come as a jupyter notebook.

**Comment by CFGrote** [comment]
Great usage instruction video https://www.youtube.com/watch?v=wYYFnPkVBrY !

**Comment by CFGrote** [comment]
In the "Trace Artifacts", the GUI crashes again when adding lines (after the 6th or 7th line).
```
$> cgt                                                       [joss-submission] 
QXcbConnection: XCB error: 3 (BadWindow), sequence: 613, resource id: 17012649, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 2641, resource id: 17022700, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 2860, resource id: 16889909, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 3418, resource id: 16902349, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 3541, resource id: 16916071, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/home/grotec/Repositories/JOSSReviews/CrystalGrowthTracker/cgt/gui/markupview.py", line 291, in mouseReleaseEvent
    self.finish_line(self.mapToScene(event.pos()))
  File "/home/grotec/Repositories/JOSSReviews/CrystalGrowthTracker/cgt/gui/markupview.py", line 339, in finish_line
    self.extend_line(point)
  File "/home/grotec/Repositories/JOSSReviews/CrystalGrowthTracker/cgt/gui/markupview.py", line 329, in extend_line
    line = self._draw_line.line()
AttributeError: 'NoneType' object has no attribute 'line'
zsh: abort      cgt
```

**Comment by jonathanHuwP** [comment]
@CFGrote @JoannaLeng @KedoKudo

1. I have removed the call to the deleted 'display_error' function. So, failure to probe the video will generate a warning message box rather than crashing the program.
2. Regarding the second bug: I have placed a guard on the offending line, to prevent execution if a line object has not been created.  I was only able to generate the error twice myself, both times running PIP installed on Linux.  Since adding the guard I have not been able to replicate the error.
3. All existing tests pass on linux and windows.

Best wishes
@jonathanHuwP

**Comment by CFGrote** [comment]
Hi,
sorry for the delay, I was on vacation. I'll reinstall and check.

**Comment by CFGrote** [comment]
Small related issue: The link to youtube videos and sample video in the paper.md (both gh rendered version and downloaded pdf) don't work.

**Comment by CFGrote** [comment]
The observed crash is not appearing anymore, so can close this issue.
